#include "duckdb/common/assert.hpp"
#include "duckdb/common/enums/join_type.hpp"
#include "duckdb/common/helper.hpp"
#include "duckdb/common/typedefs.hpp"
#include "duckdb/common/types.hpp"
#include "duckdb/common/types/value.hpp"
#include "duckdb/common/unique_ptr.hpp"
#include "duckdb/common/unordered_map.hpp"
#include "duckdb/common/vector.hpp"
#include "duckdb/execution/expression_executor.hpp"
#include "duckdb/optimizer/filter_pushdown.hpp"
#include "duckdb/optimizer/optimizer.hpp"
#include "duckdb/planner/binder.hpp"
#include "duckdb/planner/column_binding.hpp"
#include "duckdb/planner/expression/bound_columnref_expression.hpp"
#include "duckdb/planner/expression/bound_comparison_expression.hpp"
#include "duckdb/planner/expression/bound_constant_expression.hpp"
#include "duckdb/planner/expression_iterator.hpp"
#include "duckdb/planner/joinside.hpp"
#include "duckdb/planner/logical_operator.hpp"
#include "duckdb/planner/operator/logical_any_join.hpp"
#include "duckdb/planner/operator/logical_comparison_join.hpp"
#include "duckdb/planner/operator/logical_cross_product.hpp"
#include "duckdb/planner/operator/logical_dummy_scan.hpp"
#include "duckdb/planner/operator/logical_filter.hpp"
#include "duckdb/planner/operator/logical_projection.hpp"
#include <utility>

namespace duckdb {

using Filter = FilterPushdown::Filter;

static unique_ptr<Expression> ReplaceColRefWithNull(unique_ptr<Expression> root_expr,
                                                    unordered_set<TableIndex> &right_bindings) {
	ExpressionIterator::VisitExpressionMutable<BoundColumnRefExpression>(
	    root_expr, [&](BoundColumnRefExpression &bound_colref, unique_ptr<Expression> &expr) {
		    if (right_bindings.find(bound_colref.binding.table_index) != right_bindings.end()) {
			    // bound colref belongs to RHS
			    // replace it with a constant NULL
			    expr = make_uniq<BoundConstantExpression>(Value(expr->return_type));
		    }
	    });
	return root_expr;
}

static unique_ptr<LogicalOperator> CreateDummyRHS(Optimizer &optimizer, unique_ptr<LogicalOperator> &rhs_op) {
	unordered_map<TableIndex, vector<unique_ptr<Expression>>> projections_groups;
	auto column_bindings = rhs_op->GetColumnBindings();
	rhs_op->ResolveOperatorTypes();
	auto &types = rhs_op->types;

	for (idx_t i = 0; i < column_bindings.size(); i++) {
		projections_groups[column_bindings[i].table_index].emplace_back(
		    make_uniq<BoundConstantExpression>(Value(types[i])));
	}

	auto create_proj_dummy_scan = [&](TableIndex table_index) {
		auto dummy_scan = make_uniq<LogicalDummyScan>(optimizer.binder.GenerateTableIndex());
		auto proj = make_uniq<LogicalProjection>(table_index, std::move(projections_groups[table_index]));
		proj->AddChild(std::move(dummy_scan));
		return proj;
	};

	auto begin = projections_groups.begin();
	D_ASSERT(begin != projections_groups.end());
	unique_ptr<LogicalOperator> rhs = create_proj_dummy_scan(begin->first);
	projections_groups.erase(begin);

	for (auto &group : projections_groups) {
		auto proj = create_proj_dummy_scan(group.first);
		rhs = LogicalCrossProduct::Create(std::move(rhs), std::move(proj));
	}

	return rhs;
}

static bool FilterRemovesNull(ClientContext &context, ExpressionRewriter &rewriter, Expression *expr,
                              unordered_set<TableIndex> &right_bindings) {
	// make a copy of the expression
	auto copy = expr->Copy();
	// replace all BoundColumnRef expressions from the RHS with NULL constants in the copied expression
	copy = ReplaceColRefWithNull(std::move(copy), right_bindings);

	// attempt to flatten the expression by running the expression rewriter on it
	auto filter = make_uniq<LogicalFilter>();
	filter->expressions.push_back(std::move(copy));
	rewriter.VisitOperator(*filter);

	// check if all expressions are foldable
	for (idx_t i = 0; i < filter->expressions.size(); i++) {
		if (!filter->expressions[i]->IsFoldable()) {
			return false;
		}
		// we flattened the result into a scalar, check if it is FALSE or NULL
		auto val =
		    ExpressionExecutor::EvaluateScalar(context, *filter->expressions[i]).DefaultCastAs(LogicalType::BOOLEAN);
		// if the result of the expression with all expressions replaced with NULL is "NULL" or "false"
		// then any extra entries generated by the LEFT OUTER JOIN will be filtered out!
		// hence the LEFT OUTER JOIN is equivalent to an inner join
		if (val.IsNull() || !BooleanValue::Get(val)) {
			return true;
		}
	}
	return false;
}

unique_ptr<LogicalOperator> FilterPushdown::PushdownLeftJoin(unique_ptr<LogicalOperator> op,
                                                             unordered_set<TableIndex> &left_bindings,
                                                             unordered_set<TableIndex> &right_bindings) {
	auto &join = op->Cast<LogicalJoin>();
	FilterPushdown left_pushdown(optimizer, convert_mark_joins), right_pushdown(optimizer, convert_mark_joins);
	// 对于比较连接，我们创建一个FilterCombiner，用于检查是否可以将左侧连接条件上的过滤条件（LHS join conditions）
	// 推送到连接的右侧（the RHS of the join）
	FilterCombiner filter_combiner(optimizer); // 这是一个新的 FilterCombiner，收集本连接中的条件
	const auto isComparison = (op->type == LogicalOperatorType::LOGICAL_COMPARISON_JOIN ||
	                           op->type == LogicalOperatorType::LOGICAL_ASOF_JOIN);
	if (isComparison) {
		// add all comparison conditions xm: 加入的是当前连接的连接条件
		auto &comparison_join = op->Cast<LogicalComparisonJoin>();
		for (auto &cond : comparison_join.conditions) {
			if (cond.IsComparison()) {
				filter_combiner.AddFilter(make_uniq<BoundComparisonExpression>(
				    cond.GetComparisonType(), cond.GetLHS().Copy(), cond.GetRHS().Copy()));
			} else {
				filter_combiner.AddFilter(cond.GetJoinExpression().Copy());
			}
		}
	}
	// now check the set of filters
	vector<unique_ptr<Filter>> remaining_filters;
	for (idx_t i = 0; i < filters.size(); i++) {
		auto side = JoinSide::GetJoinSide(filters[i]->bindings, left_bindings, right_bindings);
		if (side == JoinSide::LEFT) { // xm: 左连接上面的只依赖左侧的过滤条件，我们可以直接推送到左侧
			// bindings match left side
			// we can push the filter into the left side
			if (isComparison) {
				// 我们可能也能够将它下推到右侧，但仅当它是一个与连接谓词匹配的比较操作时
				// 我们使用FilterCombiner来确定这一点，将表达式添加到FilterCombiner中 xm: L.id = R.id，L.id = 5
				filter_combiner.AddFilter(filters[i]->filter->Copy());
			}
			left_pushdown.filters.push_back(std::move(filters[i]));
			// erase the filter from the list of filters
			filters.erase_at(i);
			i--;
		} else if (op->type != LogicalOperatorType::LOGICAL_ASOF_JOIN) {
			// bindings匹配右侧或两侧：我们不能直接将其下推到右侧
			// 然而，如果过滤器从右侧移除了包含空值的行，我们可以将左外连接
			// 转换为内连接，然后像内连接那样进行下推
			// 编辑：这只在bindings匹配两侧时才可能，这样过滤器可以下推到两个子节点
			// 如果过滤器只能应用于右侧，且过滤器过滤了所有元组，那么内连接就无法转换。
			if (FilterRemovesNull(optimizer.context, optimizer.rewriter, filters[i]->filter.get(), right_bindings)) {
				// the filter removes NULL values, turn it into an inner join
				join.join_type = JoinType::INNER;
				// 现在我们可以进行更多的下推操作
				// 将我们添加到 left_pushdown 的所有过滤器移回过滤器列表中
				for (auto &left_filter : left_pushdown.filters) {
					filters.push_back(std::move(left_filter));
				}
				for (auto &filter : remaining_filters) {
					filters.push_back(std::move(filter));
				}
				// now push down the inner join
				return PushdownInnerJoin(std::move(op), left_bindings, right_bindings);
			}
			// we should keep the filters which do not remove NULL values
			remaining_filters.push_back(std::move(filters[i]));
			filters.erase_at(i);
			i--;
		}
	}
	// xm: 现在，上面的谓词在remaining_filters中，连接条件在filter_combiner中，我们已经将所有可以直接下推到左侧的过滤器下推到了左侧
	// 但是还没有往右侧下推

	// 最后，我们检查FilterCombiner，查看是否有任何谓词可以下推到右侧表
	// 我们只添加了：(1) 条件中具有JoinSide::BOTH的谓词，以及
	// (2) 过滤器中具有JoinSide::LEFT的谓词
	// 现在我们检查这种组合是否生成了任何仅作用于JoinSide::RIGHT的新过滤器
	// 这种情况会在例如：连接条件为 (i=a) 且存在过滤器 (i=500) 时发生，
	// 此时我们可以将过滤器 (a=500) 下推到右侧表
	filter_combiner.GenerateFilters([&](unique_ptr<Expression> filter) { // 这是本层的 FilterCombiner，生成条件并尝试下推
		if (JoinSide::GetJoinSide(*filter, left_bindings, right_bindings) == JoinSide::RIGHT) {
			right_pushdown.AddFilter(std::move(filter)); // 下推到右侧
		}
	});
	right_pushdown.GenerateFilters(); // 这是右子树的FilterCombiner，FilterCombiner -> 右侧filters
	op->children[0] = left_pushdown.Rewrite(std::move(op->children[0]));

	// 接下来检查一下，连接条件是否一定为false，如果是的话，可以简化成： 左子树 cross join null行
	bool rewrite_right = true;
	bool has_unsatisfiable_condition = false;

	if (op->type == LogicalOperatorType::LOGICAL_COMPARISON_JOIN) {
		auto &comparison_join = join.Cast<LogicalComparisonJoin>();
		for (auto &cond : comparison_join.conditions) {
			if (!cond.IsComparison()) {
				if (AddFilter(cond.GetJoinExpression().Copy()) == FilterResult::UNSATISFIABLE) {
					has_unsatisfiable_condition = true;
					break;
				}
			}
		}
	} else if (op->type == LogicalOperatorType::LOGICAL_ANY_JOIN) {
		auto &any_join = join.Cast<LogicalAnyJoin>();
		if (AddFilter(any_join.condition->Copy()) == FilterResult::UNSATISFIABLE) {
			has_unsatisfiable_condition = true;
		}
	}

	// if unsatisfiable and LEFT JOIN - replace RHS with dummy scan
	if (has_unsatisfiable_condition && join.join_type == JoinType::LEFT) {
		auto dummy_rhs = CreateDummyRHS(optimizer, op->children[1]);
		op = LogicalCrossProduct::Create(std::move(op->children[0]), std::move(dummy_rhs));
		rewrite_right = false;
	}

	if (rewrite_right) {
		op->children[1] = right_pushdown.Rewrite(std::move(op->children[1]));
	}

	for (auto &filter : remaining_filters) {
		filters.push_back(std::move(filter));
	}

	return PushFinalFilters(std::move(op));
}

} // namespace duckdb
